---
- name: Create AMPCamp data folder
  file: path=/{{ ampcamp_container }} state=directory
  tags: 
    - install

- name: Download AMPCamp wikistats dataset from SoftLayer Object Store
  # do not change indentation in the long line below
  shell: >
    if [ ! -d /{{ ampcamp_container }}/{{ item }} ]; then 
    cd /{{ ampcamp_container }};
    swift -A {{ swift_api_url }} 
    -U {{ swift_user }} -K {{ swift_key }} 
    download {{ ampcamp_container }} --prefix {{ item }}; 
    fi 
  with_items:
    - wikistats_20090505-01
    - wikistats_20090505_restricted-01
    - movielens
    - wiki_links
    - training.tar.gz
  tags:
    - install

- name: Put AMPCamp data from /ampcamp-data to HDFS
  shell: >
    su - {{ hdfsuser }} -c "hadoop fs -mkdir -p /wiki/pagecounts";
    su - {{ hdfsuser }} -c "hadoop fs -put /{{ ampcamp_container }}/wikistats_20090505-01/* /wiki/pagecounts/";
    su - {{ hdfsuser }} -c "hadoop fs -put /{{ ampcamp_container }}/wikistats_20090505_restricted-01 /";
    su - {{ hdfsuser }} -c "hadoop fs -put /{{ ampcamp_container }}/wiki_links /";
    su - {{ hdfsuser }} -c "hadoop fs -put /{{ ampcamp_container }}/movielens /";
  # ignore errors if already exists
  ignore_errors: true
  tags:
    - configure

- name: Unpack training stuff to /root
  unarchive: copy=no src="/{{ ampcamp_container }}/training.tar.gz" dest=/root/
  tags:
    - install

- name: Create some symlinks for convenience
  file: src=/root/training/{{ item }} dest=/root/{{ item }} state=link
  with_items:
    - java-app-template
    - machine-learning
    - scala-app-template
    - streaming
  tags:
    - install

- name: Create /root/spark-ec2 directory to store configs required by AMPCamp examples
  file: path=/root/spark-ec2 state=directory
  tags:
    - install

- include_vars: roles/spark_standalone/vars/main.yml
  tags:
    - configure

- name: Create config files required by AMPCamp examples MLlib and GraphX
  template: src={{ item }}.j2 dest=/root/spark-ec2/{{ item }}
  with_items:
    - cluster-url
    - masters
  tags:
    - configure

