---
- name: Create /tmp on HDFS
  shell: su - {{ hdfsuser }} -c "hadoop fs -mkdir /tmp"
  # ignore errors if file exists
  ignore_errors: true

- name: Upload Spark package to HDFS
  shell: su - {{ hdfsuser }} -c "hadoop fs -put /tmp/spark-{{ spark['spark_version'] }}.tgz /tmp"
  # ignore errors if file exists
  ignore_errors: true

- name: Configure Spark to use Mesos
  template: src=conf/spark-env.sh.j2 dest=/opt/spark/conf/spark-env.sh

- name: increase default spark.executor.memory parameter
  template: src=conf/spark-defaults.conf.j2 dest={{ spark['spark_root'] }}/conf/spark-defaults.conf
