---
java_playbook_version: "0.1.4" # playbook version
java_version: "7"
java_libjvm_path: "/usr/lib/jvm/java-{{java_version}}-*/jre/lib/*/server/libjvm.so"
java_libjvm_symlink_path: "/usr/lib/libjvm.so"
