---
- name: Download Shark pre-built package
  get_url: url={{ shark_download_url }} dest="/tmp/shark-{{ shark_version }}.tgz"
  tags:
    - install

- name: Extract Shark archive
  unarchive: copy=no src="/tmp/shark-{{ shark_version }}.tgz" dest=/opt/
  tags:
    - install

- name: Create link to Shark directory
  file: src=/opt/shark-{{ shark_version }} dest=/opt/shark state=link
  tags:
    - install

- include_vars: roles/hadoop_common/vars/main.yml
  tags:
    - configure

- include_vars: roles/spark_standalone/vars/main.yml
  tags:
    - configure

- include_vars: roles/mesos/vars/main.yml
  tags:
    - configure

- include_vars: roles/hive/vars/main.yml
  tags:
    - configure

- name: Configure Shark to run in standalone deploy mode
  template: src=conf/shark-env.sh.j2 dest=/opt/shark/conf/shark-env.sh
  tags:
    - configure

- name: Fix protobuf bug by replacing the hive-exec jar 
  # https://groups.google.com/forum/#!topic/shark-users/0pGIVQvaYfo
  # it is very important not to change indentation in the long line below
  shell: >
    cd /opt/shark/lib_managed/jars/edu.berkeley.cs.shark/hive-exec;
    mv hive-exec-0.11.0-shark-0.9.1.jar hive-exec-0.11.0-shark-0.9.1.jar.orig;
  tags:
    - install

- get_url: >
  url=http://10abe.http.sjc01.cdn.softlayer.net/ampcamp-data/hive-exec-0.11.0-shark-0.9.1.jar
  dest=/opt/shark/lib_managed/jars/edu.berkeley.cs.shark/hive-exec/hive-exec-0.11.0-shark-0.9.1.jar
  tags:
    - install
