---
- name: install some tools for convenience
  apt: name={{ item }} state=present
  with_items:
    - vim
    - tmux
    - git
    - htop
    - nmon
    - build-essential
    - python-swiftclient
    - libgfortran3

- name: populate /etc/hosts
  template: src=etc/hosts.j2 dest=/etc/hosts

