cassandra_cluster_name: "Test Cluster"
# if use different name, make sure to update system.local table
# on all nodes
# http://stackoverflow.com/questions/22006887/cassandra-saved-cluster-name-test-cluster-configured-name

seed_node_ip: "{{ hostvars[groups['master'][0]]['ansible_' + iface]['ipv4']['address'] }}"
cassandra_version: 2.0.16
